# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-Dependency
version:      1.02
version_from: lib/Algorithm/Dependency.pm
installdirs:  site
requires:
    File::Spec:                    0.83
    Test::ClassAPI:                0.6
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
