name: Algorithm-Dependency
version: 1.04
abstract: Toolkit for implementing dependency systems
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
  Test::ClassAPI: 0.6
requires:
  perl: 5.005
  Params::Util: 0.05
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
