
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 1.102
name: Algorithm-Dependency
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
  Test::ClassAPI: 0.6
requires: 
  List::Util: 1.11
  perl: 5.005
  Params::Util: 0.06
abstract: Base class for implementing various dependency trees
