---
abstract: 'Base class for implementing various dependency trees'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::ClassAPI: 0.6
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.83'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Algorithm::Dependency
name: Algorithm-Dependency
no_index:
  directory:
    - inc
    - t
requires:
  List::Util: 1.11
  Params::Util: 0.31
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Algorithm-Dependency
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Algorithm-Dependency
version: 1.110
